version: '3.8'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: Your_database_username
        MONGO_INITDB_ROOT_PASSWORD: Your_database_password
        MONGO_INITDB_DATABASE: product-service 
    volumes:
      - ./data:/data/db